# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Russell Hicks
title: Technical lead and experienced manager
email: russell@scapegrace.co.uk
website: www.rustynailor.co.uk

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username:  rustynailor
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: rustynailor
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hands on technical lead with agency and startup experience. Proven leadership and management skills.  20+ years working in development and leadership roles in mobile and web.  
  
  Pragmatic problem solver.  Firm believer in the importance of building kind, nurturing working environments that deliver maximum ROI  by enabling everyone to reach their full potential. 
  
  Proficient in Kotlin, Java, Android development, Typescript, Laravel, VueJS and database design. Agile enthusiast. 
  
  Looking to find a home  at a company where I can make a real difference.


content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bond Digital Health
        sub_title: CTO
        caption: MARCH  2019 - SEPTEMBER 2022
        quote: >
          A universal data capture platform for the lateral flow industry
        description: | # this will include new lines to allow paragraphs
          Developed prototype versions of the main API, web and mobile apps, as well as acting as sole developer on several successful R&D projects in association with Swansea University. 
          
          Designed and implemented Agile based workflows and practices appropriate for the digital healthcare space. 
          
          Led recruitment to scale the development team from two to a 20 strong unit, including taking on line management and review responsibilities.  
          
          Introduced a CI based deployment workflow that drastically reduced testing time and enabled automated build delivery to clients. 
          
          Successfully delivered releases of Transform to our main US client, including securing app store approval and FDA authorisation, to supply Covid test reporting  to consumers and businesses across North America. 

      - layout: left
        title: Rantmedia
        sub_title: CTO
        caption: JANUARY 2015 - FEBRUARY 2019
        quote: >
          Lead developer at a BAFTA winning mobile development studio
        description: | # this will include new lines to allow paragraphs
          Led a cross platform native mobile and web development team at Rantmedia, a leading UK mobile agency.  
          
          Highlights include work on a BAFTA winning cross platform game, designing a CI driven cross platform build system and shepherding the team towards a more test-driven approach to development, improving code quality and reducing reported bugs. 
          
          Successfully delivered projects for dozens of clients during my four years here. Originally recruited as a systems architect then promoted to CTO in 2016.

      - layout: left
        title: Various clients
        sub_title: Freelance Web and Mobile Developer
        caption: JANUARY 2014 - DECEMBER 2015
        quote: >
          Mobile and web freelance work with clients in Cardiff, London and Bristol
        description: | # this will include new lines to allow paragraphs
          Worked as the sole developer on projects for various clients including a Laravel based timesheet tracking system, an Android app designed to help people give up smoking and a digital asset management system for a chain of estate agents.

      - layout: left
        title: Subhub
        sub_title: Senior Software Engineer
        caption: APRIL 2012 - DECEMBER 2013
        quote: >
          PHP/Drupal based SASS platform for content providers
        description: | # this will include new lines to allow paragraphs
          Senior developer on Wordpress and Drupal-based paywall subscription content management systems.

      - layout: left
        title: Big Eye Deers
        sub_title: Technical Director
        caption: SEPTEMBER 2009 – JANUARY 2011
        quote: >
          Cardiff based agency with great designs
        description: | # this will include new lines to allow paragraphs
          Co-founder and lead developer at Magento and Wordpress web agency.

      - layout: left
        title: Inexus
        sub_title: Software Developer / Digital Marketing Manager
        caption: NOVEMBER 2004 – AUGUST 2009
        quote: >
          (Now defunct) Independent utility infrastructure installation and management
        description: | # this will include new lines to allow paragraphs
          Worked as a developer on a PL/SQL Oracle 8 based internal asset management product. Promoted to Marketing manager and led development and marketing team in multiple web projects for Inexus products and companies.



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cardiff University
        caption: 2003 - 2004
        sub_title: MSc Computer Science
        quote: >
          A solid foundation in programming and computer science on this MSc conversion course at a Russell Group University.
        description: | # this will include new lines to allow paragraphs
          Java, OOP, database design, UML, discrete mathematics, data structures and algorithms - an excellent foundation for a career in software development.      

      - layout: left
        title: Cardiff University
        caption: 1997 - 2000
        sub_title: BA English Literature
        quote: >
          Developed communication, problem solving and analysis skills (and a slightly useless lifelong love of desolate, alcohol soaked interwar literature).
        description: | # this will include new lines to allow paragraphs
          Degree class 2:1


  - title: A little more about me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in technology and software engineering some of my other hobbies are:
      - Writing (Short stories and longer fiction)
      - Politics (Many nerdy podcasts consumed)
      - Cinema
      - Hiking


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
