# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Russell Hicks
title: Technical Lead and Experienced Manager
email: russell@scapegrace.co.uk
website: www.rustynailor.co.uk

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username:  rustynailor
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: rustynailor
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hands on technical lead with agency and startup experience. Proven leadership and management skills.  20+ years working in development and leadership roles in mobile and web.  
  
  Pragmatic problem solver.  Firm believer in the importance of building kind, nurturing working environments that deliver maximum ROI  by enabling everyone to reach their full potential. 
  
  Proficient in Kotlin, Java, Android development, Typescript, Laravel, VueJS and database design. Agile enthusiast. 
  
  Looking to find a home  at a company where I can make a real difference.


content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bond Digital Health
        sub_title: CTO
        caption: MARCH  2019 - SEPTEMBER 2022,  CARDIFF
        quote: >
          Lead development of a universal data capture platform for the lateral flow industry
        description: | # this will include new lines to allow paragraphs
          Developed prototype versions of the main API, web and mobile apps, as well as acting as sole developer on several successful R&D projects in association with Swansea University. 
          
          Designed and implemented Agile based workflows and practices appropriate for the digital healthcare space. 
          
          Led recruitment to scale the development team from two to a 20 strong unit, including taking on line management and review responsibilities.  
          
          Introduced a CI based deployment workflow that drastically reduced testing time and enabled automated build delivery to clients. 
          
          Successfully delivered releases of Transform to our main US client, including securing app store approval and FDA authorisation, to supply Covid test reporting  to consumers and businesses across North America. 

      - layout: left
        title: Rantmedia
        sub_title: CTO
        caption: JANUARY 2015 - FEBRUARY 2019
        quote: >
          Lead developer at a BAFTA winning mobile development studio
        description: | # this will include new lines to allow paragraphs
          Led a cross platform native mobile and web development team at Rantmedia, a leading UK mobile agency.  
          
          Highlights include work on a BAFTA winning cross platform game, designing a CI driven cross platform build system and shepherding the team towards a more test-driven approach to development, improving code quality and reducing reported bugs. 
          
          Successfully delivered projects for dozens of clients during my four years here. Originally recruited as a systems architect then promoted to CTO in 2016. 


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cardiff University
        caption: 2003 - 2004
        sub_title: MSc Computer Science
        
       - layout: left
       title: Cardiff University
       caption: 1997 - 2000
       sub_title: BA English Literature


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Writing (Short stories and longer fiction)
      - Politics nerdiness
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
